on: [push, pull_request]

name: Build and Deploy Glossary Website

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.1
      with:
          persist-credentials: false

    - name: Setup Ruby and Bundler
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 2.6 # Not needed with a .ruby-version file

    - name: Build site
      run: bundle install && make gh-site

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GH_PAT_DEPLOY }}
        BRANCH: gh-pages
        FOLDER: _site
